"""add table changes

Revision ID: a6cdc12bc2ce
Revises: 
Create Date: 2021-03-29 19:16:55.090162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cdc12bc2ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheetlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('composer', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('published_on', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheetlist')
    # ### end Alembic commands ###
